# Generated by Django 3.1.3 on 2021-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(max_length=600)),
                ('UMobile', models.CharField(max_length=600)),
                ('UEmail', models.CharField(max_length=600)),
                ('UState', models.CharField(max_length=600)),
                ('UWallet', models.CharField(max_length=600)),
                ('URefbyCode', models.CharField(max_length=600)),
            ],
        ),
    ]
